version: '3.4'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo